# Target Python 3.11+
target-version = "py311"
line-length = 120

[lint]
# Enable Pyflakes (F), Pycodestyle (E, W), Isort (I), and Flake8-bugbear (B)
select = ["F", "E", "W", "I", "B", "UP"]
ignore = ["E501"] # Line too long (handled by formatter)

[lint.isort]
combine-as-imports = true
force-single-line = false
